### ISSUE TITLE
Please add screenshots of the other themes

### ISSUE THREAD

**Issue by unixorn** [fusion809/zsh-theme#1]
I'd like to add this to [awesome-zsh-plugins](https://github.com/unixorn/awesome-zsh-plugins), but I prefer to add themes with screen shots so that users can see what they look like without having to install them. Please add screenshots of hfulldate and hornix.

Also, please consider either putting the different theme files in subdirectories or separate repositories so they're easier to use by people using ZSH frameworks like [zgen](https://github.com/tarjoilija/zgen) or [antigen](https://github.com/zsh-users/antigen).

Thanks!

**Comment by fusion809** [comment]
I'm honoured by your belief these themes are worthy of this, so I shall be happy to oblige.
